workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main3' && $CI_PIPELINE_SOURCE == 'push'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build

build-job:
  stage: build
  tags:
    - macos
  image: maven:3.9-eclipse-temurin-21
  script:
    - echo "пакуем наш проект..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day
