workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main3'

stages:
  - build

build-and-test-job:
  stage: build
  tags:
    - saas-linux-small-amd64
  image: eclipse-temurin:21-jdk
  script:
    - echo "packaging the project..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar
