workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main3' && $CI_PIPELINE_SOURCE == 'push'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - macos
  image: maven:3.9-eclipse-temurin-21
  script:
    - echo "пакуем наш проект..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

semgrep-sast:
  stage: test
  tags:
    - macos
  image: returntocorp/semgrep
  variables:
    GIT_STRATEGY: clone
  script:
    - semgrep scan --config=auto --gitlab-sast --output=gl-sast-report.json .
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
    expire_in: 1 week

sca-analysis:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn dependency-check:check
  artifacts:
    paths:
      - target/dependency-check-report.html
    when: always
  tags:
    - macos
