# .github/workflows/java-build.yml

name: Java CI Build on Pull Request

on:
  pull_request:
    branches: [ "main3" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build with Maven
        run: |
          if [ -f ./mvnw ]; then
            echo "Maven Wrapper found. Using ./mvnw"
            chmod +x ./mvnw
            ./mvnw -B package
          else
            echo "Maven Wrapper not found. Using mvn from container"
            mvn -B package
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-application
          path: target/*.jar
